export const USA_STATE_LIST = [
  "Alabama",
  "Alaska",
  "American Samoa",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "District of Columbia",
  "Federated States of Micronesia",
  "Florida",
  "Georgia",
  "Guam",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Marshall Islands",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Northern Mariana Islands",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Palau",
  "Pennsylvania",
  "Puerto Rico",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virgin Island",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];

export const COUNTRY_LIST = [
  "United States",
  "Germany",
  "Belgium",
  "United Kingdom",
  "Canada",
  "Spain",
  "Italy",
  "France",
  "Portugal",
  "Greece",
  "Estonia",
  "Denmark",
  "Sweden",
  "Norway",
  "Switzerland",
  "Ukraine",
  "Serbia",
  "Poland",
  "Crotia",
  "Austria",
];

export const CANADA_PROVINCES = [
  "Alberta",
  "British Columbia",
  "Manitoba",
  "New Brunswick",
  "Newfoundland and Labrador",
  "Northwest Territories",
  "Nova Scotia",
  "Nunavut",
  "Ontario",
  "Prince Edward Island",
  "Quebec",
  "Saskatchewan",
  "Yukon Territory",
];
export const GERMANY_STATES = [
  "Berlin",
  "Bayern",
  "Niedersachsen",
  "Baden-Württemberg",
  "Rheinland-Pfalz",
  "Sachsen",
  "Thüringen",
  "Hessen",
  "Nordrhein-Westfalen",
  "Sachsen-Anhalt",
  "Brandenburg",
  "Mecklenburg",
  "Hamburg",
  "Schleswig-Holstein",
  "Saarland",
  "Bremen",
];
